version: "3.9"
services:
  db:
    image: postgres:16-bookworm
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB}"]
      interval: 5s
      timeout: 30s
      retries: 5
